[package]
name = "neuron"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
thiserror = "1"
serde = { version = "1", features = ["derive"] }
futures = "0.3"

protocol = { path = "../protocol" }
model-runtime = { path = "../model-runtime" }
cache = { path = "../cache" }
